### ISSUE TITLE
This is a Guide on how to deploy to Github Pages using Github Actions

### ISSUE THREAD

**Issue by dmastag** [arnehilmann/markdeck#49]
Though as per @arnehilmann from #21 :

> One of the ideas behind markdeck is the possibility to preview your slides before you have to check in your changes. 

But I still think that after you are done previewing your slides you might want to automate the build.

Below is what is working for me

```
name: publish-slides
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  built-slides:
      runs-on: ubuntu-latest
      steps:
        - uses: actions/checkout@v2
        - name: build
          run: |
            cd slides/src #Folder where your main slides are
            curl -LO https://raw.githubusercontent.com/arnehilmann/markdeck/master/markdeck
            chmod a+x markdeck
            ./markdeck once
        
        - name: Deploy 🚀
          uses: JamesIves/github-pages-deploy-action@3.6.2
          with:
            GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
            BRANCH: gh-pages # The branch the action should deploy to.
            FOLDER: slides/src/deck # The folder the action should deploy.
            CLEAN: true # Automatically remove deleted files from the deploy branch
```

Of course you could also have markdeck already in your repository.
